// This component simulates personalized recommendations that require real-time processing
// It will be part of the dynamic portion in PPR

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Simulate fetching personalized recommendations
async function fetchRecommendations() {
  // Simulate network delay for AI/ML processing
  await delay(1200);

  const categories = [
    "electronics",
    "accessories",
    "books",
    "clothing",
    "home",
    "sports",
  ];
  const reasons = [
    "Based on your recent purchases",
    "Trending in your area",
    "Similar customers also bought",
    "Perfect for the season",
    "Recommended by our AI",
    "Popular this week",
  ];

  // Generate random recommendations
  return Array.from({ length: 4 }, (_, i) => ({
    id: i + 1,
    title: `Recommended Product ${i + 1}`,
    category: categories[Math.floor(Math.random() * categories.length)],
    reason: reasons[Math.floor(Math.random() * reasons.length)],
    price: Math.floor(Math.random() * 200) + 20,
    rating: (Math.random() * 2 + 3).toFixed(1), // 3.0 - 5.0
    discount: Math.floor(Math.random() * 30) + 10, // 10-40% off
  }));
}

export default async function DynamicRecommendations() {
  const recommendations = await fetchRecommendations();

  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <div className="space-y-4">
        {recommendations.map((item) => (
          <div
            key={item.id}
            className="flex items-center space-x-4 p-3 bg-gray-50 rounded-lg"
          >
            <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center">
              <span className="text-purple-600 font-semibold">{item.id}</span>
            </div>

            <div className="flex-grow">
              <h4 className="font-medium text-gray-900">{item.title}</h4>
              <p className="text-sm text-gray-600 capitalize">
                {item.category}
              </p>
              <p className="text-xs text-blue-600">{item.reason}</p>
            </div>

            <div className="text-right">
              <div className="flex items-center space-x-2">
                <span className="text-lg font-semibold text-green-600">
                  ${item.price}
                </span>
                <span className="text-xs bg-red-100 text-red-600 px-2 py-1 rounded">
                  {item.discount}% off
                </span>
              </div>
              <div className="flex items-center mt-1">
                <span className="text-yellow-400 text-sm">★</span>
                <span className="text-sm text-gray-600 ml-1">
                  {item.rating}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 pt-4 border-t">
        <div className="flex items-center justify-between">
          <p className="text-xs text-gray-500">
            🤖 Generated by ML algorithms in real-time
          </p>
          <button className="text-xs text-purple-600 hover:text-purple-700 font-medium">
            Refresh Recommendations
          </button>
        </div>
      </div>
    </div>
  );
}
